### ISSUE TITLE
Create a requirements.txt file

### ISSUE THREAD

**Issue by HugooB** [kaustubhhiware/facebook-archive#1]
Hi man! Great work on creating exactly what I wanted to do with my Facebook archive! I'm trying to run your scripts, but I'm afraid some libraries (or the right versions) are missing. Could you make a `requirements.txt` file, so that people can easily run it?

Check out this link to see how:
http://www.idiotinside.com/2015/05/10/python-auto-generate-requirements-txt/

**Comment by kaustubhhiware** [comment]
Thanks for pointing this out!
Will immediately get this done.

**Comment by HugooB** [comment]
Thanks! 👍
