### ISSUE TITLE
Messages > Top 10 friends that message you

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/facebook-archive#17]
Plot number of messages with each friend as a function of time. Since this could get messy, plot only top 10-20 friends.

This could include treating any message exchange as a message, or 
it could have two plots:
- top 10 friends by who message you
- top 10 friends who you message

**Comment by darthgera123** [comment]
i would like to work on this issue

**Comment by xprilion** [comment]
@darthgera123 can you please brief how you may be solving this issue (just a few short sentences)? Will assign it to you right after.

**Comment by darthgera123** [comment]
what im planning is collect the data(need to figure that out) an plot the results using matplotlib. I was planning on using fbchat library.Tried building something like this 6 months ago though lol

**Comment by xprilion** [comment]
please take a look at the current project requirements in the requirements.txt file..do you think this task is possible to be done using those modules? 

> collect the data(need to figure that out) an plot the results using matplotlib

Have you went through the readme of the project? We already have data available in json format. Need not collect anymore. And by brief I'd suggest you to underline how you would implement precisely the features in this task.. :)

**Comment by kaustubhhiware** [comment]
@darthgera123 It seems you haven't read the README or even the project name at all!

By your approach we mean given the facebook-archive data, what are the things that you can explore in the current issue's context ?

**Comment by darthgera123** [comment]
Sorry I  didn't go through that. What I am planning is that with the given data I will plot the number of messages exchanged with every guy. Along with that since sender is specified the given task can be achieved .

**Comment by kaustubhhiware** [comment]
Closed with #32
