### ISSUE TITLE
Friends > Plot friends only since the last year

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/facebook-archive#28]
## Description
Extend functionality of plot_friends.py to specify from and to period. Currently doing for all time. 
Something of the type: `python plot_friends.py --from 2018-12-01`, should support both `--from` and `--to` flags, both optional.

## Steps to reproduce (Incase of a bug)
NA

### Update [Required]
- [ ] Support `--from` and `--to` flags in plot_friends.py
### Enhancement to Update [Optional]
- [x] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours after having an idea of original code

**Comment by kaustubhhiware** [comment]
@GalenWong you're welcome to :smile: !

Assigning this issue to you. Just have a look at plot_friends.py and make the necessary changes to support the suggested flags.

**Comment by aditya9706** [comment]
hi, I would like to contribute to the issue.

**Comment by kaustubhhiware** [comment]
Hi @aditya9706!
Sure, have a look at #30 for reference.

P. S: This project is no longer a part of open code, if you wish to have your contribution accounted for there.
