### ISSUE TITLE
README python version issue

### ISSUE THREAD

**Issue by GalenWong** [kaustubhhiware/facebook-archive#29]
## Description
The README file indicates the code uses python 2.7.

However, when I tried to run `plot_friends.py`, the given example gives an error. 

```
$ python plot_friends.py
Enter facebook archive extracted location: ./examples
Traceback (most recent call last):
  File "plot_friends.py", line 87, in <module>
    friends(loc)
  File "plot_friends.py", line 22, in friends
    loc = input('Enter facebook archive extracted location: ')
  File "<string>", line 1
    ./examples
    ^
SyntaxError: invalid syntax
```
This is because the python 2.7 `input` function expects a python expression that can be executed. 

## Mocks
N/A

## Steps to reproduce (Incase of a bug)
- Use python 2.7 
- Install required dependency `pip install -r requirements.txt`
- run `python plot_friends`
- input `./exmaples`

### Update [Required]
Choose Either one of the solutions:
- Change to python 3.x on the README file
- Change to `raw_input` instead of `input`
- Use command line argument instead of having the user input it manually (recommended)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by kaustubhhiware** [comment]
Does the issue persist when the location input is given as `examples` in the above example?

Regardless, I'm in favour of updating the README to python 3.x. Thanks for pointing this out.

**Comment by kaustubhhiware** [comment]
@GalenWong you could answer this issue in your plot_friends work that is currently ongoing, for the `--from` flag support.

**Comment by kaustubhhiware** [comment]
I don't think the PR would be too big since your change would affect only two files, README and plot_friends.py.

**Comment by kaustubhhiware** [comment]
> > Does the issue persist when the location input is given as examples in the above example?
> Yes, it will still be an issue. Since if we put examples to stdin, input function evaluates it as if there is a examples variable somewhere in the scope.

The script executes just fine with `examples` as an input.

**Comment by GalenWong** [comment]
@kaustubhhiware I tested it with python version 2.7 and behavior matches my expected result. 

```bash
# Using python 2
$ python plot_friends.py
Enter facebook archive extracted location: examples
Traceback (most recent call last):
  File "plot_friends.py", line 129, in <module>
    loc = input('Enter facebook archive extracted location: ')
  File "<string>", line 1, in <module>
NameError: name 'examples' is not defined
```

I assume you were using python3, which then should not give an error.

**Comment by kaustubhhiware** [comment]
I'm sorry I should have been clear. Yes, we'll be shifting to python3. Please make the changes as you find appropriate. 

If you think you need 2-3 PR's for friends `--from` flag, making the original `plot_friends` handle corner cases, and this; please proceed as per your discretion.
