### ISSUE TITLE
Friends > Did you send them a request or they did?

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/facebook-archive#7]
This is an addition over the current feature.
 How many friends you make, based on received friend requests, and requests you sent. For each day, you have 2 entries, friends you made who sent you requests, and friends you sent a request to. (ed

**Comment by parimatrix** [comment]
Hi. I think I could work on this issue too. It should not be too complex. The only thing would be again extracting names from the text for each date. Can this issue be please assigned to me?
Thanks!

**Comment by kaustubhhiware** [comment]
I sure appreciate your enthusiasm, but I'm reluctant to assign you 2 issues at the same time before seeing any of your contributions. Please complete the assigned issue first, I don't mind assigning you this issue as soon as you are done there.

**Comment by parimatrix** [comment]
Okay, sure. I understand totally.

**Comment by parasjain-12** [comment]
I think I can work on this issue please assign me.

**Comment by kaustubhhiware** [comment]
@parasjain-12 please share your vision about this issue.

Before we assign this issue to you, what are the things you seek to solve with a PR?
I'm sort of reluctant to assign this issue since another participant has expressed interest on working on this.

**Comment by parasjain-12** [comment]
We can create a list of all those who had send the request and list of friend those request you have received. We can also create a graphical representation like in which month you have send maximum friend and in which month you have received a maximum request

**Comment by kaustubhhiware** [comment]
@parasjain-12 have you had a look at the corresponding file in your own archive regarding this?

The archive already has a JSON for this, creating a list is very trivial !
I mean to ask, what are the features do you wish to implement?

From your description, you wish to add:
- Which months you have sent maximum friend requests
- Which months you have received most friend requests

I assume these are plots?

**Comment by parasjain-12** [comment]
Yes, I can also add any other features you wish to implement.

**Comment by kaustubhhiware** [comment]
If you have seen the existing plots, we have depicted number of friends made every day. I'm suggesting 2 more plots

1) It might be interesting to see how many friends you make every day of these received / sent, along with total (3 lines in one plot, sent(s) , received(r), total)

2) and what percent of friends you make every month (Jan 2017 and Jan 2018 as different months) by percentage.
Say, Jun 2017 70% of new friends you made were those who sent you a friend request, Jul 2017 it's 60%

A bar chart might be interesting, to see whether as you grow, do you send out less friend requests?
See below images, x-axis has different months, y-axis has max value has 100 (because 100%) and each bar has only 2 colors, one for friends you had sent a request (in yellow), and other who had sent you a request (in red).

![jquery-chart-percentage-stacked-column-series](https://user-images.githubusercontent.com/11318551/41859795-993eb76c-78ba-11e8-828b-af81f48d5c7f.png)

**Comment by parasjain-12** [comment]
Yaa sure I can do that

**Comment by parimatrix** [comment]
@kaustubhhiware I have no problems in Paras working on this issue. Since I am working on another one, why to delay the work on this issue. As soon as I finish my current issue, will look for other open issues.
Thanks !

**Comment by kaustubhhiware** [comment]
That's the spirit @parimatrix !
Chalo, will be doing that without guilt now.
@parasjain-12 please have a look at the archive, previous merged PRs to get an idea of what is expected.

**Comment by techytushar** [comment]
@parasjain-12 any updates on the progress?

**Comment by parasjain-12** [comment]
I have already done the first part.I just have to add legend . And the second part is in the process.

**Comment by parasjain-12** [comment]
I am stuck a little bit where to ask the question?
